# Generated by Django 5.0.2 on 2024-02-24 11:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chatbox", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="box",
            options={"verbose_name": "Box", "verbose_name_plural": "Boxes"},
        ),
    ]
